### ISSUE TITLE
Github login fails

### ISSUE THREAD

**Issue by ntomka** [bolt/marketplace-site#52]
Hi!

I tried to login with github to the extension site, but got this error:

![screen2](https://cloud.githubusercontent.com/assets/2313363/16686911/98f18d3c-4515-11e6-9772-01730336e4d4.png)

Am I doing something wrong? :)

**Comment by GawainLynch** [comment]
I am guessing it is due to your account not being associated yet … which is still a bit (OK, a lot) rough around the edges.

The current "trick" is to follow these steps:
  1. Set your email address on your GitHub account to publicly visible (temporary)
  2. Login using user name & password
  3. Go to this link and do the GitHub login https://extensions.bolt.cm/authentication/login
  4. Change your GitHub email visibility back to what it was

The root cause is that the Members extension needs an email account as the primary ID for any account, and when logging in via OAuth and an email address isn't available from the provider, it should ask you to register one … but I haven't hooked that up yet on productions … because time :wink:

**Comment by ntomka** [comment]
Setting my email to public solved the issue. Thanks!

> because time

I know that feel bro'! :smiley:
